// Compiled by ClojureScript 1.12.42 {:optimizations :none}
goog.provide('tic_tac_toe.spec_helper');
goog.require('cljs.core');
goog.require('tic_tac_toe.core');
tic_tac_toe.spec_helper.gui_mock_state = (function tic_tac_toe$spec_helper$gui_mock_state(){
return tic_tac_toe.core.initial_state.call(null,new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"interface","interface",394869923),new cljs.core.Keyword(null,"gui","gui",604532813),new cljs.core.Keyword(null,"save","save",1850079149),new cljs.core.Keyword(null,"mock","mock",-383657858)], null));
});
tic_tac_toe.spec_helper.state_create = (function tic_tac_toe$spec_helper$state_create(p__13931){
var map__13932 = p__13931;
var map__13932__$1 = cljs.core.__destructure_map.call(null,map__13932);
var cells = cljs.core.get.call(null,map__13932__$1,new cljs.core.Keyword(null,"cells","cells",-985166822));
var x_difficulty = cljs.core.get.call(null,map__13932__$1,new cljs.core.Keyword(null,"x-difficulty","x-difficulty",1381668443),null);
var x_type = cljs.core.get.call(null,map__13932__$1,new cljs.core.Keyword(null,"x-type","x-type",-337186212),null);
var board = cljs.core.get.call(null,map__13932__$1,new cljs.core.Keyword(null,"board","board",-1907017633),null);
var response = cljs.core.get.call(null,map__13932__$1,new cljs.core.Keyword(null,"response","response",-1068424192));
var active_player_index = cljs.core.get.call(null,map__13932__$1,new cljs.core.Keyword(null,"active-player-index","active-player-index",-93298655),(0));
var interface$ = cljs.core.get.call(null,map__13932__$1,new cljs.core.Keyword(null,"interface","interface",394869923));
var save = cljs.core.get.call(null,map__13932__$1,new cljs.core.Keyword(null,"save","save",1850079149),new cljs.core.Keyword(null,"mock","mock",-383657858));
var status = cljs.core.get.call(null,map__13932__$1,new cljs.core.Keyword(null,"status","status",-1997798413),new cljs.core.Keyword(null,"welcome","welcome",-578152123));
var o_type = cljs.core.get.call(null,map__13932__$1,new cljs.core.Keyword(null,"o-type","o-type",-1512862507),null);
var o_difficulty = cljs.core.get.call(null,map__13932__$1,new cljs.core.Keyword(null,"o-difficulty","o-difficulty",1887923991),null);
var G__13933 = new cljs.core.PersistentArrayMap(null, 4, [new cljs.core.Keyword(null,"board","board",-1907017633),board,new cljs.core.Keyword(null,"active-player-index","active-player-index",-93298655),active_player_index,new cljs.core.Keyword(null,"status","status",-1997798413),status,new cljs.core.Keyword(null,"players","players",-1361554569),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"character","character",380652989),"X",new cljs.core.Keyword(null,"play-type","play-type",519061088),x_type,new cljs.core.Keyword(null,"difficulty","difficulty",755680807),x_difficulty], null),new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"character","character",380652989),"O",new cljs.core.Keyword(null,"play-type","play-type",519061088),o_type,new cljs.core.Keyword(null,"difficulty","difficulty",755680807),o_difficulty], null)], null)], null);
var G__13933__$1 = (((!((cells == null))))?cljs.core.assoc.call(null,G__13933,new cljs.core.Keyword(null,"cells","cells",-985166822),cells):G__13933);
var G__13933__$2 = (((!((interface$ == null))))?cljs.core.assoc.call(null,G__13933__$1,new cljs.core.Keyword(null,"interface","interface",394869923),interface$):G__13933__$1);
var G__13933__$3 = (((!((response == null))))?cljs.core.assoc.call(null,G__13933__$2,new cljs.core.Keyword(null,"response","response",-1068424192),response):G__13933__$2);
if((!((save == null)))){
return cljs.core.assoc.call(null,G__13933__$3,new cljs.core.Keyword(null,"save","save",1850079149),save);
} else {
return G__13933__$3;
}
});
tic_tac_toe.spec_helper.empty_board = new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(1),(2),(3)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(4),(5),(6)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(7),(8),(9)], null)], null);
tic_tac_toe.spec_helper.empty_4_board = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [(1),(2),(3),(4)], null),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [(5),(6),(7),(8)], null),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [(9),(10),(11),(12)], null),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [(13),(14),(15),(16)], null)], null);
tic_tac_toe.spec_helper.empty_3d_board = new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(1),(2),(3)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(4),(5),(6)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(7),(8),(9)], null)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(10),(11),(12)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(13),(14),(15)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(16),(17),(18)], null)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(19),(20),(21)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(22),(23),(24)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(25),(26),(27)], null)], null)], null);
tic_tac_toe.spec_helper.center_x_board = new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(1),(2),(3)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(4),"X",(6)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(7),(8),(9)], null)], null);
tic_tac_toe.spec_helper.first_X_4_board = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [(1),(2),(3),(4)], null),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [(5),"X",(7),(8)], null),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [(9),(10),(11),(12)], null),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [(13),(14),(15),(16)], null)], null);
tic_tac_toe.spec_helper.first_x_3d_board = new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(1),(2),(3)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(4),(5),(6)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(7),"X",(9)], null)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(10),(11),(12)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(13),(14),(15)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(16),(17),(18)], null)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(19),(20),(21)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(22),(23),(24)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(25),(26),(27)], null)], null)], null);

//# sourceMappingURL=spec_helper.js.map
